// ======================================================================
// Scenario sequences + tests for the wb_dma RTL UVM environment.
//
// THE SCHEME: a uvm_test is a broad CATEGORY (an env configuration and a
// verdict policy); a CASE is a virtual sequence the test looks up by name from
// `+SEQ=`. Adding a case adds a vseq here and a cell in tests/uvm/flow.yaml --
// the test hierarchy does not grow with the regression.
//
// One class per .svh, each after what it depends on:
//   base seq       -- the device API and every register-semantics caveat
//   unit seqs      -- one programmed transfer, parameterized by their caller
//   vseq base      -- what makes a sequence selectable by +SEQ=
//   scenario vseqs -- a whole case: arrange, act, check; no parameters
//   base test      -- builds the env, runs the named vseq, reports the verdict
// ======================================================================
`include "uvm_macros.svh"

package wb_dma_tests_pkg;
    import uvm_pkg::*;
    import fwvip_wb_xtor_pkg::*;
    import fwvip_wb_pkg::*;
    import wb_dma_env_pkg::*;

    // The PSS model, as SystemVerilog: the runtime base classes and the
    // generated export API / factory (zsp_gen_pkg). Generated by the `pss-sv`
    // task from src/pss and compiled ahead of this package.
    import zsp_rt_pkg::*;
    import zsp_gen_pkg::*;

    // device API
    `include "wb_dma_base_seq.svh"

    // unit sequences: one transfer, parameters supplied by a scenario
    `include "wb_dma_sw_copy_seq.svh"
    `include "wb_dma_arb_seq.svh"
    `include "wb_dma_err_seq.svh"

    // scenarios, selected by +SEQ=<type>
    `include "wb_dma_vseq.svh"
    `include "wb_dma_sw_copy_vseq.svh"
    `include "wb_dma_arb_vseq.svh"
    `include "wb_dma_err_vseq.svh"
    `include "pss_hello_world_vseq.svh"

    // test categories
    `include "wb_dma_base_test.svh"
endpackage
